
version: '3.8'

services:
  my-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '8082:8082'
    volumes:
      - ./my-app:/var/www/my-app
    healthcheck:
      disable: true

volumes:
  notused: